### ISSUE TITLE
Clarify support terms for this & related extensions

### ISSUE THREAD

**Issue by xurizaemon** [compucorp/uk.co.compucorp.membership#2]
I see there are several extensions on Github of this type which seem related:

* https://github.com/compucorp/uk.co.compucorp.membership
* https://github.com/coolbit/uk.co.compucorp.membershipperiod
* https://github.com/alok0590/CiviCRM-Membership-Period-Extension

For CiviCRM sites looking for an extension and finding these on Github, it would be good to clarify whether these are supported extensions, learning/research projects, or something else.

Ensuring that each of these extensions contains a notice in the README and `info.xml` description to clarify the nature of the extension to sites might prevent sites installing something that doesn't work or is unsupported.

**Comment by xurizaemon** [comment]
I think it's awesome Compucorp are introducing new contributors to the ecosystem!

I propose that if Compucorp  ask people to write an extension as a code exercise (which I think this is?), you add a requirement that they mention the scope and purpose of work shared until it is ready for prime time. This can help to combat "noise" / confusion in the contribution space.

Thanks!

**Comment by jamienovick** [comment]
Will do Chris, thanks for flagging this.

**Comment by xurizaemon** [comment]
Ah cool, I mistook it for one of the others and thought this would be the most central place to discuss.
